project_id = "eeshomcqztvjkvycdfwi"

[functions.delete-user]
verify_jwt = true

[functions.send-password-recovery]
verify_jwt = false

[functions.send-signup-confirmation]
verify_jwt = false

[functions.bet-delay-processor]
verify_jwt = false

[functions.populate-batalla-gimnasios]
verify_jwt = false

[functions.admin-ai-assistant]
verify_jwt = false

[functions.fetch-sports-news]
verify_jwt = false

[functions.publish-news-to-social]
verify_jwt = false

[functions.send-fighter-invitation]
verify_jwt = true

[functions.send-license-approval]
verify_jwt = true

[functions.send-mass-email]
verify_jwt = true

[functions.fetch-link-metadata]
verify_jwt = false

[functions.ai-strike-ingest]
verify_jwt = false

[functions.ai-strike-test-simulator]
verify_jwt = false

[functions.finalize-fight-auto]
verify_jwt = false

[functions.receive-contact]
verify_jwt = false

[functions.notify-admin-pending]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.remove-image-background]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.send-gym-invitation]
verify_jwt = false
