project_id = "eeshomcqztvjkvycdfwi"

[functions.bet-delay-processor]
verify_jwt = false

[functions.populate-batalla-gimnasios]
verify_jwt = false

[functions.admin-ai-assistant]
verify_jwt = false

[functions.fetch-sports-news]
verify_jwt = false