#!/usr/bin/env bash
# Untrack .env from git (run locally, then push).
# .env is auto-managed by Lovable and contains only the publishable (anon) key,
# but should never be committed.
set -euo pipefail

if git ls-files --error-unmatch .env >/dev/null 2>&1; then
  echo "Untracking .env..."
  git rm --cached .env
  git commit -m "chore(security): untrack .env (regenerated by Lovable)"
  echo "Done. Push with: git push"
else
  echo ".env is not tracked. Nothing to do."
fi
